# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
fabric.loom.disableObfuscation=true
# Mod properties
mod_version=2.2000.1.1-pre2
maven_group=io.github.wen-wen520
archives_name=magpie-bridge
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.3
# Dependencies
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3
neoforge_version=26.3.0.39-beta
architectury_api_version=22.0.3
cloth_config_version=26.3.159
mod_menu_version=21.0.0
